config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :users, only: [:show]
  resources :posts

  resources :posts do
    resources :likes
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :dashboard, only: [:index]
  get '/home', to: "home#index"

  # Root route
  root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord

  # associations
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable

  # validations
  validates :content, presence: :true, length: { maximum: 100 }

  # scope
  default_scope -> { order(created_at: :desc) }
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :get_commentable, only: [:new, :create]
    before_action :allowed?, only: [:destroy]

    def new
      @comment = Comment.new
    end

    def create
      @comment = @commentable.comments.new comment_params
      @comment.user_id = current_user.id
      if @comment.save
        @commentable.update_attribute(:comments_count, @commentable.comments_count + 1)
        redirect_to posts_path, notice: 'Comment posted successfully!'
      else
        redirect_to posts_path, notice: "Something Went wrong. Please try agian later!"
      end
    end

    def destroy
      commentable = @comment.commentable
      commentable.update_attribute(:comments_count, commentable.comments_count - 1)
      @comment.destroy
      flash[:notice] = "Comment deleted successfully!"
      redirect_to root_url
    end

    private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def get_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
    end

    def allowed?
      @comment = current_user.comments.find_by(id: params[:id])
      redirect_to root_url unless @comment or current_user.admin?
    end
end

app/views/comments/_comment.html.slim
.comments.card-panel
  .row.user-info.valign-wrapper
    .avatar.col.s2
      = user_avatar(comment.user.image)
    .comment-info.left.col.s8
      span.user-name
        = link_to comment.user.name, comment.user
      br
      span.comment
        = comment.content
      br
      span.posted-time
        = time_ago(comment.created_at)
    br
    .comment-actions.col.s2
      - if current_user == comment.user or current_user.admin?
        span.right.destroy
          = link_to post_comment_path(comment.commentable, comment), method: :delete, class: 'red-text', data: { confirm: "Are you sure, you want to delete?" } do
            i.tooltipped.fas.fa-trash data-position='top' data-tooltip='Delete Comment'