config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :users, only: [:show]
  resources :posts

  resources :posts do
    resources :likes
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :dashboard, only: [:index]
  get '/home', to: "home#index"

  # Root route
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord

  # mounting uploader for image
  mount_uploader :avatar, AvatarUploader
  
  # associations
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :likes, dependent: :destroy

  #validations
  validates :user_id, presence: :true
  validates :content, length: { maximum: 250 }

  # scope
  default_scope -> { order(created_at: :desc) }

  # to check image attached
  def avatar_attached?
    self.avatar.present?
  end

  # to return the image name
  def image
    self.avatar.filename
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :signed_in?
    before_action :post_owner?, only: :destroy

    helper ApplicationHelper
    
    def create
      @post = current_user.posts.new(post_params)
      if @post.save
        flash[:notice] = "Post created successfully!"
      else
        flash[:error] = "Something went wrong!"
      end
      redirect_to root_url
    end

    def index
      @post  = current_user.posts.build
      @posts = Post.all.includes(:user, :likes, :comments)
    end

    def show
      @post = Post.find(params[:id])
    end

    def destroy
      @post.destroy
      flash[:notice] = "Post deleted successfully!"
      redirect_to request.referrer || root_url  
    end

    private

    def post_params
      params.require(:post).permit(:content, :avatar)
    end

    def post_owner?
      @post = Post.find_by(id: params[:id])
      redirect_to root_url unless @post or current_user.admin?
    end
end

app/views/posts/_form.html.slim
.row
  = form_with model: @post, class: "col s12", id: 'postForm' do |f|
    .row
      .input-field.col.s12
        i.far.fa-comment.prefix
        = f.text_area :content, placeholder: "What's on your mind ?.", class: "materialize-textarea"

      .file-field.input-field.col.s12
        .btn
          i.fas.fa-image
          span &nbsp; Photo
          = f.file_field :avatar, accept: 'image/jpeg,image/gif,image/png', id: "post_picture"
        .file-path-wrapper
          input.file-path.file-path-text.validate type="text"
    .row
      .submit-btn.center
        = f.submit "Post", class: "btn btn-primary"

app/views/posts/_post.html.slim
.card-panel.hoverable
  .post-info
    .row.user-info.valign-wrapper
      .avatar.col.s2
        = user_avatar(post.user.image)
      .post-info.col.s8
        span.user-name
          = link_to post.user.name, post.user
        br
        span.posted-time
          = time_ago(post.created_at)
      .post-actions.col.s2
        - unless params[:controller] == 'dashboard'
          - if current_user == post.user or current_user.admin?
            span.right.destroy
              = link_to post, method: :delete, class: 'red-text', data: { confirm: "Are you sure, you want to delete?" } do
                i.tooltipped.fas.fa-trash data-position='top' data-tooltip='Delete Post'
  
  .content
    span = post.content
  br
  .image
    - if post.avatar_attached?
      = cl_image_tag(post.image, class: 'responsive-img materialboxed', data: {caption: post.content})
  br
  .counts
    span.likes_count
      = count_with_text(post.likes_count, 'Like')
    span &nbsp;
    span.right.tooltipped.comments_count.comments-toggler.cursor-pointer data-postid="post#{post.id}" data-position='top' data-tooltip='Click to View Comments'
      = count_with_text(post.comments_count, 'Comment')
  hr
  - unless params[:controller] == 'dashboard'
    .likes-comments
      span.pre-like
        - pre_like = like_unlike(post, current_user)
        - if pre_like
          = link_to post_like_path(post, pre_like), method: :delete do
            span.tooltipped.far.fa-thumbs-down data-position='top' data-tooltip='Unlike'
        - else
          = link_to post_likes_path(post), method: :post do
            span.tooltipped.far.fa-thumbs-up.2x data-position='top' data-tooltip='Like'
      span &nbsp;
      span.comments.cursor-pointer
        i.tooltipped.far.fa-comments.commentForm-toggler data-position='top' data-tooltip='Comment' data-postid="post#{post.id}"

  .row.card-panel.comment-form id="post#{post.id}-comment-form"
    = form_for [post, Comment.new], class: "col s12" do |f|
      .row
        .input-field.col.s8
          = f.text_area :content, placeholder: "Add a comment", class: 'materialize-textarea'
        .submit-btn.col.s2
          = f.submit "Post Comment", class: "btn-small"
  
  .comments-section id="post#{post.id}-comments"
    ul.collection
      = render partial: 'comments/comment', collection: post.comments

app/views/posts/_posts.html.slim
- if posts.any?
  ol.posts
    = render partial: 'post', collection: posts

app/views/posts/index.html.slim
.row
  .col.l3
  .col.l6.s12
    .row.card-panel
      = render 'form'
    .row
      .card-panel.col-md-8.post-feed
        = render partial: 'posts', locals: { posts: @posts }
  .col.l3