config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :users, only: [:show]
  resources :posts

  resources :posts do
    resources :likes
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :dashboard, only: [:index]
  get '/home', to: "home#index"

  # Root route
  root "posts#index"
end

app/views/layouts/_navbar.html.slim
.navbar-fixed
  nav
    .nav-wrapper.grey.darken-3
      a.brand-logo href="/posts"  Social Networking
      a.sidenav-trigger data-target="mobile-menu" href="#"
        i.material-icons menu
      
      ul.right.hide-on-med-and-down
        = render partial: 'layouts/navbar_links'
      
ul#mobile-menu.sidenav
  = render partial: 'layouts/navbar_links'

app/views/layouts/_navbar_links.html.slim
- if user_signed_in?
  li
    = link_to 'Posts', posts_path
  li
    = link_to 'Dashboard', dashboard_index_path
  li
    = link_to current_user.name, user_path(current_user)

  li
    = link_to destroy_user_session_path, method: :delete do
      i.fas.fa-sign-out-alt
      | &nbsp; LOGOUT
- else
  li
    = link_to new_user_registration_path do
      i.fa.fa-user-plus
      | &nbsp; SIGN UP
  li
    = link_to new_user_session_path do
      i.fas.fa-sign-in-alt
      | &nbsp; LOGIN

app/views/layouts/application.html.slim
doctype html
html
  head
    title Sample Social Networking
    meta name="description" content="UserManagement"
    meta name="google-site-verification" content="jkwhu-LTob8vLLxlof1hSZuScrEzqm6DdtbZrj6zKu4"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags

    meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"
  body
    = render partial: 'layouts/navbar'

    .container.main-wrapper
      - if notice
        span.notice.hide
          = notice
          br
      - if alert
        span.alert.hide
          = alert
          br
    .row
    = yield